# fly.toml app configuration file generated for projectcloudapp on 2025-07-29T18:25:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'projectcloudapp'
primary_region = 'bog'

[build]
  [build.args]
    PORT = "8080"  # Fuerza el puerto

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  processes = ["app"]

[env]
  PORT = "8080"  # Doble garantía

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
